name: Run Allure + Playwright Tests and Deploy Reports

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Run Allure + Vitest tests
      - name: Run Allure Vitest Tests
        run: |
          npm run test:allure
          mkdir -p reports/allure-vitest
          cp -r allure-report/* reports/allure-vitest/

      # Run Playwright tests
      - name: Run Playwright Tests
        run: |
          npx playwright install --with-deps
          npx playwright test --reporter=html
          mkdir -p reports/playwright
          cp -r playwright-report/* reports/playwright/

      # Deploy both reports
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports
