name: Run Allure (Vitest) + Playwright Tests in Parallel and Deploy Reports

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # 🧪 Job 1 — Run Allure (Vitest) tests
  allure-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./front-end
        run: npm install

      - name: Run Vitest with Allure
        working-directory: ./front-end
        run: |
          npm run test:report
          npx allure generate ./allure-results --clean -o ../allure-report-vite

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report-vite

  # 🎭 Job 2 — Run Playwright E2E tests
  playwright-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: remoteuser
          MYSQL_PASSWORD: mypassword
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Load environment variables
        run: |
          cp back-end/server/.env.ci back-end/server/.env

      - name: Install backend dependencies
        working-directory: ./back-end/server
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./front-end
        run: npm install

      - name: Install Playwright dependencies
        working-directory: ./e2e-tests
        run: |
          npm install
          npx playwright install --with-deps

      - name: Initialize MySQL Database
        run: |
          sudo apt-get install -y mysql-client
          echo "⏳ Waiting for MySQL..."
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "✅ MySQL ready!"
              break
            fi
            sleep 5
          done
          mysql -h127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS testdb;"
          if [ -f back-end/server/init.sql ]; then
            mysql -h127.0.0.1 -uroot -proot testdb < back-end/server/init.sql
          fi

      - name: Start backend
        working-directory: ./back-end/server
        env:
          NODE_ENV: test
          PORT: 5001
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: root
          DB_NAME: testdb
          DB_PORT: 3306
          JWT_SECRET: test_secret
        run: |
          nohup node server.js > backend.log 2>&1 &
          echo "⏳ Waiting for backend..."
          for i in {1..20}; do
            if curl -s http://127.0.0.1:5001/health > /dev/null; then
              echo "✅ Backend is up!"
              break
            fi
            sleep 3
          done

      - name: Start frontend
        working-directory: ./front-end
        run: |
          nohup npm run dev -- --host > frontend.log 2>&1 &
          echo "⏳ Waiting for frontend..."
          for i in {1..20}; do
            if curl -s http://127.0.0.1:5173 > /dev/null; then
              echo "✅ Frontend is running!"
              break
            fi
            sleep 3
          done

      - name: Run Playwright tests
        working-directory: ./e2e-tests
        env:
          API_BASE_URL: http://127.0.0.1:5001
        run: |
          npx playwright test --reporter=html
          mkdir -p ../playwright-report
          cp -r playwright-report ../playwright-report

      - name: Upload Playwright report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  # 🚀 Job 3 — Combine reports & deploy (runs after both finish)
  deploy:
    runs-on: ubuntu-latest
    needs: [allure-tests, playwright-tests]
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: combined-report/allure-report

      - name: Download Playwright report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: combined-report/playwright-report

      - name: Create index page
        run: |
          cat <<EOF > combined-report/index.html
          <html>
            <head>
              <title>Test Reports Dashboard</title>
              <style>
                body { font-family: Arial, sans-serif; background: #fafafa; text-align: center; padding: 60px; }
                h1 { color: #222; }
                .link { display: block; margin: 20px auto; width: 250px; padding: 15px; background: #0078d4; color: white; border-radius: 10px; text-decoration: none; font-weight: bold; }
                .link:hover { background: #005fa3; }
              </style>
            </head>
            <body>
              <h1>✅ Test Reports Dashboard</h1>
              <a class="link" href="./allure-report/index.html">📊 View Allure (Vitest) Report</a>
              <a class="link" href="./playwright-report/index.html">🎭 View Playwright Report</a>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: combined-report
          publish_branch: gh-pages
          force_orphan: true

      - name: Show Report URL
        run: |
          echo "## ✅ Reports Published Successfully" >> $GITHUB_STEP_SUMMARY
          echo "- [Open Reports](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)" >> $GITHUB_STEP_SUMMARY
