name: Initialize gh-pages Branch

# This workflow is triggered manually from the GitHub Actions tab
on: workflow_dispatch

jobs:
  create:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Create and Push gh-pages branch
        run: |
          # Configure Git user (required before pushing)
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 1. Create a new, orphan branch called gh-pages
          git switch --orphan gh-pages
          
          # 2. Remove all files from the new branch
          git rm -rf .
          
          # 3. Create a README to establish the first commit
          echo "GitHub Pages branch for Allure Report" > README.md
          
          # 4. Commit the new file
          git add README.md
          git commit -m "Initialize gh-pages branch"
          
          # 5. Push the new branch to remote
          git push origin gh-pages
