name: Run tests and publish report (Node.js/Allure)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checks out your repository code
      - uses: actions/checkout@v3
      
      # Step 2: Sets up the Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 
          
      # --- START FRONT-END-SPECIFIC STEPS ---
      
      # Step 3: Install Node dependencies
      - name: Install Front-end Dependencies
        run: npm install
        # CRITICAL: Run this command inside the 'front-end' directory
        working-directory: front-end

      # Step 4: Runs the Node.js test command, generating Allure results (JSON files)
      - name: Run Front-end Tests & Generate Results
        run: npm test
        # CRITICAL: Run this command inside the 'front-end' directory
        working-directory: front-end
        
      # Step 5: Load previous report history from the gh-pages branch
      - name: Load test report history
        uses: actions/checkout@v3 
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      # Step 6: Build the Allure HTML report
      # The allure-results are now expected to be in front-end/allure-results
      - name: Build Allure HTML Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          # Tell Allure where to find the JSON files (relative to root)
          allure_results: front-end/allure-results
          # Directory where the final HTML report will be created
          gh_pages: allure_report
          allure_history: allure-history

      # Step 7: Publishes the final HTML report to the gh-pages branch for GitHub Pages viewing
      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          # publish_dir is set to the final HTML output directory
          publish_dir: allure_report
          force_orphan: true
