name: Run tests and publish Allure report

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository (FIXED: Added token for fetch permission)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Ensures permissions for subsequent branch fetching

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: front-end

      # 4️⃣ Run tests (generate Allure results)
      - name: Run tests and generate Allure results
        run: npm test 
        working-directory: front-end

      # 5️⃣ Load previous Allure report history
      - name: Load previous Allure report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-prev-history 

      # 6️⃣ Build Allure report
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: front-end/allure-results
          gh_pages: allure-prev-history
          allure_history: allure-report-html 

      # 7️⃣ Publish Allure report to gh-pages
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report-html
          force_orphan: true
