name: Run tests and publish Allure report (Monorepo)

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # NEW: Add permissions for accessing Pages information
    permissions:
      contents: write
      pages: write 

    steps:
      # 1️⃣ Checkout the repository (Added token for fetch permission)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Needed for fetching gh-pages later

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies (FIX: Added working-directory)
      - name: Install dependencies
        run: npm ci
        working-directory: front-end 

      # 4️⃣ Run tests (FIX: Added working-directory & changed script to 'npm test')
      - name: Run tests and generate Allure results
        # Assuming your package.json uses 'npm test' or you have configured it
        run: npm test 
        working-directory: front-end 

      # 5️⃣ Load previous Allure report history
      - name: Load previous Allure report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-prev-history

      # 6️⃣ Build Allure report (FIX: Corrected allure_results path)
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          # Results are inside the front-end folder
          allure_results: front-end/allure-results
          gh_pages: allure-prev-history
          allure_history: allure-history

      # 7️⃣ Publish Allure report to gh-pages
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        id: deployment # Added ID to reference this step's output
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true 

      # 8️⃣ NEW STEP: Display the live URL as a job summary output
      - name: Display Live Report URL
        if: success()
        run: |
          echo "## ✅ Allure Report Published" >> $GITHUB_STEP_SUMMARY
          echo "The live report is available here:" >> $GITHUB_STEP_SUMMARY
          # Uses the output URL generated by the peaceiris/actions-gh-pages action
          echo "- [Live Report Link](${{ steps.deployment.outputs.page_url }})" >> $GITHUB_STEP_SUMMARY
