name: Run tests and publish Allure report

on:
  push:
    branches: [ main ]  # Change if your main branch has a different name

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        # CRITICAL FIX: Run command inside the front-end folder
        working-directory: front-end

      # 4️⃣ Run tests (generate Allure results)
      - name: Run tests and generate Allure results
        run: npm run test:allure # Ensure this is the correct script name in your package.json
        # CRITICAL FIX: Run command inside the front-end folder
        working-directory: front-end

      # 5️⃣ Load previous Allure report history
      - name: Load previous Allure report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: allure-prev-history # Folder to store the history loaded from gh-pages

      # 6️⃣ Build Allure report
      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          # Tell Allure where to find the JSON files (relative to root)
          allure_results: front-end/allure-results
          # Folder where the history was loaded from
          gh_pages: allure-prev-history
          # Folder where the new HTML report will be created for publishing
          allure_history: allure-report-html # Renamed from allure-history to be clearer

      # 7️⃣ Publish Allure report to gh-pages
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          # Publish the newly built HTML report folder
          publish_dir: allure-report-html
          force_orphan: true
